// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceDay.API.Data;

#nullable disable

namespace RaceDay.API.Migrations
{
    [DbContext(typeof(RaceDayDbContext))]
    partial class RaceDayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaceDay.Api.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("eventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("eventDate");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("eventName");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("eventType");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<int>("OrganiserId")
                        .HasColumnType("int")
                        .HasColumnName("organiserID");

                    b.HasKey("EventId");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Event", null, t =>
                        {
                            t.HasCheckConstraint("CK_Event_EventType", "[eventType] IN ('Run', 'Walk', 'Cycle')");
                        });
                });

            modelBuilder.Entity("RaceDay.Api.Models.EventCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("AgeRange")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ageRange");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoryName");

                    b.Property<string>("Distance")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("distance");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventID");

                    b.HasKey("CategoryId");

                    b.HasIndex("EventId", "CategoryName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Category_Event_Name");

                    b.ToTable("Event_Categories", (string)null);
                });

            modelBuilder.Entity("RaceDay.Api.Models.EventEnrolment", b =>
                {
                    b.Property<int>("EnrolmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrolmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrolmentId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<DateTime>("EnrolmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("enrolmentDate")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventID");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participantID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Registered")
                        .HasColumnName("status");

                    b.HasKey("EnrolmentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId", "EventId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Enrolment_Participant_Event_Category");

                    b.ToTable("Event_Enrolment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrolment_Status", "[status] IN ('Registered', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RaceDay.Api.Models.EventOrganiser", b =>
                {
                    b.Property<int>("OrganiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("organiserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganiserId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("OrganiserId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventOrganiser_UserID");

                    b.ToTable("Event_Organiser", (string)null);
                });

            modelBuilder.Entity("RaceDay.Api.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("participantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("ParticipantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Participant_UserID");

                    b.ToTable("Participant", (string)null);
                });

            modelBuilder.Entity("RaceDay.Api.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resultID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("DateOfResults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("dateOfResults")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.Property<int>("EnrolmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrolmentID");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("time")
                        .HasColumnName("finishTime");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.HasKey("ResultId");

                    b.HasIndex("EnrolmentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Result_EnrolmentID");

                    b.ToTable("Results", null, t =>
                        {
                            t.HasCheckConstraint("CK_Result_Position", "[position] > 0");
                        });
                });

            modelBuilder.Entity("RaceDay.Api.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("routeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<decimal>("Distance")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("distance");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventID");

                    b.Property<string>("MapURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mapURL");

                    b.Property<string>("RouteDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("routeDescription");

                    b.HasKey("RouteId");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Route_EventID");

                    b.ToTable("Route", (string)null);
                });

            modelBuilder.Entity("RaceDay.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("contactNumber");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emailAddress");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("userName");

                    b.HasKey("UserId");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_EmailAddress");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RaceDay.Api.Models.Event", b =>
                {
                    b.HasOne("RaceDay.Api.Models.EventOrganiser", null)
                        .WithMany()
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Event_Organiser");
                });

            modelBuilder.Entity("RaceDay.Api.Models.EventCategory", b =>
                {
                    b.HasOne("RaceDay.Api.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Category_Event");
                });

            modelBuilder.Entity("RaceDay.Api.Models.EventEnrolment", b =>
                {
                    b.HasOne("RaceDay.Api.Models.EventCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrolment_Category");

                    b.HasOne("RaceDay.Api.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrolment_Event");

                    b.HasOne("RaceDay.Api.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrolment_Participant");
                });

            modelBuilder.Entity("RaceDay.Api.Models.EventOrganiser", b =>
                {
                    b.HasOne("RaceDay.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Organiser_User");
                });

            modelBuilder.Entity("RaceDay.Api.Models.Participant", b =>
                {
                    b.HasOne("RaceDay.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Participant_User");
                });

            modelBuilder.Entity("RaceDay.Api.Models.Result", b =>
                {
                    b.HasOne("RaceDay.Api.Models.EventEnrolment", null)
                        .WithMany()
                        .HasForeignKey("EnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Result_Enrolment");
                });

            modelBuilder.Entity("RaceDay.Api.Models.Route", b =>
                {
                    b.HasOne("RaceDay.Api.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Route_Event");
                });
#pragma warning restore 612, 618
        }
    }
}
